### ISSUE TITLE
ask nicely how?

### ISSUE THREAD

**Issue by gnmarten** [SkalskiP/awesome-chatgpt-code-interpreter-experiments#2]
the "ask nicely" bits are the secret sauce. Could you please share how to build up a relationship of trust by divulging inside knowledge of environment structure etc?

**Comment by SkalskiP** [comment]
Hi @gnmarten 👋🏻 I probably won't be sharing that publicly. I don't want to run into trouble with OpenAI.

**Comment by ketul93** [comment]
<img width="804" alt="image" src="https://github.com/SkalskiP/awesome-chatgpt-code-interpreter-experiments/assets/10497402/a29f8687-b88d-4cba-aaf7-ca59759f9587">
It's not that much complex ... Just do trial and error ... you will be bale to get it

**Comment by Thoss123** [comment]
It doesnt work for me though i did the steps from github from skalskiP and pasted the prompt you provided. @ketul93

**Comment by SkalskiP** [comment]
Did you try any jailbreaking techniques?
